import type {
  PropAugment,
  AugmentMethodParam,
} from '../analyzer/parser/middleware-augment-extractor';
import type { ImportRegistry } from './import-registry';

/**
 * Adapter-provided mapping from a context's first augment-path segment to a
 * TypeScript interface and its declaring module.
 *
 * Example for HttpContext:
 * ```ts
 * {
 *   request:  { interface: 'HttpRequest',  module: '@zipbul/http-adapter' },
 *   response: { interface: 'HttpResponse', module: '@zipbul/http-adapter' },
 * }
 * ```
 *
 * The compiler is protocol-agnostic — it reads this map from the adapter's
 * `defineAdapter()` config rather than hardcoding HTTP semantics.
 */
export interface AugmentTargetMap {
  readonly [namespace: string]: AugmentTargetEntry;
}

export interface AugmentTargetEntry {
  /** TypeScript interface name to augment via declaration merging. */
  readonly interface: string;
  /** Module specifier the interface lives in. */
  readonly module: string;
}

/**
 * Per-context-type adapter mapping.
 *
 * Key is the context class name passed to `ctx.to(<Type>)` (e.g. `HttpContext`).
 * Value is the namespace → interface map for that context.
 */
export interface ContextAdapterMap {
  readonly [contextType: string]: AugmentTargetMap;
}

/**
 * One middleware's contribution.
 */
export interface MiddlewareContextAugment {
  /** The middleware identifier (for diagnostics / source comments). */
  readonly middlewareName: string;
  /** The context class this middleware narrows to (e.g. `'HttpContext'`). */
  readonly contextType: string;
  /** Source file path of the middleware (for import resolution of the type identifiers). */
  readonly sourceFilePath: string;
  /** Property/method augmentations the middleware applies. */
  readonly augments: readonly PropAugment[];
  /**
   * Resolved import sources for class identifiers used in `new X(...)` augments.
   * Map from identifier name → absolute file path of its declaration.
   */
  readonly classImports: ReadonlyMap<string, string>;
}

/**
 * Generates `.zipbul/context.d.ts` — a declaration merging file that adds
 * middleware-contributed properties/methods to adapter context interfaces.
 *
 * Protocol-agnostic: takes a `ContextAdapterMap` describing which TypeScript
 * interface each context+namespace pair augments. The generator itself knows
 * nothing about HTTP, request/response, or any specific adapter.
 *
 * @public
 */
export class ContextTypesGenerator {
  /**
   * Generates the full `context.d.ts` content from a list of middleware
   * augmentations.
   *
   * @param augments - All registered middleware augmentations.
   * @param registry - Import registry for deterministic, deduplicated imports.
   * @param adapterMap - Adapter-provided context+namespace → interface mapping.
   * @returns The generated `.d.ts` source string.
   */
  generate(
    augments: readonly MiddlewareContextAugment[],
    registry: ImportRegistry,
    adapterMap: ContextAdapterMap,
  ): string {
    const grouped = this.groupByModuleAndInterface(augments, adapterMap, registry);
    const blocks: string[] = [];

    for (const [moduleName, interfaces] of grouped) {
      blocks.push(this.renderModuleBlock(moduleName, interfaces));
    }

    const importLines = registry.getImportStatements()
      .map(line => line.replace(/^import \{/, 'import type {'));
    const header = '// AUTO-GENERATED by Zipbul AOT — DO NOT EDIT.\n// Generated from registered middleware factory bodies.';

    return `${header}\n\n${importLines.join('\n')}\n\n${blocks.join('\n\n')}\n`;
  }

  /**
   * Group augments by `(module, interface)` based on the adapter map.
   * Augments whose namespace is not in the adapter map are silently dropped
   * — caller is responsible for diagnostics.
   */
  private groupByModuleAndInterface(
    augments: readonly MiddlewareContextAugment[],
    adapterMap: ContextAdapterMap,
    registry: ImportRegistry,
  ): Map<string, Map<string, string[]>> {
    // module → interface → rendered prop lines
    const out = new Map<string, Map<string, string[]>>();

    for (const aug of augments) {
      const namespaceMap = adapterMap[aug.contextType];

      if (!namespaceMap) continue;

      for (const prop of aug.augments) {
        if (prop.path.length < 2) continue;

        const namespace = prop.path[0]!;
        const target = namespaceMap[namespace];

        if (!target) continue;

        const remainder = prop.path.slice(1);
        const line = this.renderProp(remainder, prop, aug, registry);

        if (!line) continue;

        let interfaceMap = out.get(target.module);

        if (!interfaceMap) {
          interfaceMap = new Map<string, string[]>();
          out.set(target.module, interfaceMap);
        }

        const lines = interfaceMap.get(target.interface) ?? [];

        lines.push(line);
        interfaceMap.set(target.interface, lines);
      }
    }

    return out;
  }

  private renderModuleBlock(moduleName: string, interfaces: Map<string, string[]>): string {
    const lines: string[] = [];

    lines.push(`declare module '${moduleName}' {`);

    for (const [iface, props] of interfaces) {
      lines.push(`  interface ${iface} {`);
      lines.push(...props.map(p => `    ${p}`));
      lines.push('  }');
    }

    lines.push('}');

    return lines.join('\n');
  }

  /**
   * Renders a single augment line. `remainder` is the property path *after* the
   * adapter-mapped namespace. For a flat augment (`request.cookie`), remainder
   * is `['cookie']`. For deeper paths, only the first remainder segment becomes
   * the interface member; deeper paths are not currently supported.
   */
  private renderProp(
    remainder: readonly string[],
    prop: PropAugment,
    aug: MiddlewareContextAugment,
    registry: ImportRegistry,
  ): string | null {
    if (remainder.length === 0) return null;
    if (remainder.length > 1) return null; // nested augments not supported yet

    const memberName = remainder[0]!;

    if (prop.rhs.kind === 'class') {
      const importPath = aug.classImports.get(prop.rhs.identifier);

      if (!importPath) return null;

      const alias = registry.getAlias(prop.rhs.identifier, importPath);

      return `${memberName}: ${alias};`;
    }

    if (prop.rhs.kind === 'method') {
      const tParams = prop.rhs.typeParams.length > 0 ? `<${prop.rhs.typeParams.join(', ')}>` : '';
      const params = prop.rhs.params.map(formatMethodParam).join(', ');
      const returnType = prop.rhs.returnType ?? 'unknown';

      return `${memberName}${tParams}(${params}): ${returnType};`;
    }

    return null;
  }
}

function formatMethodParam(param: AugmentMethodParam): string {
  const type = param.type ?? 'unknown';

  return `${param.name}: ${type}`;
}
