/** @type {import('@commitlint/types').UserConfig} */
module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'header-max-length': [2, 'always', 100],
    'body-leading-blank': [2, 'always'],
    'body-max-line-length': [2, 'always', 100],
    'footer-leading-blank': [2, 'always'],
    'footer-max-line-length': [2, 'always', 100],
    'subject-case': [2, 'never', ['pascal-case', 'upper-case']],
    'subject-full-stop': [2, 'never', '.'],
    'scope-case': [2, 'always', ['kebab-case']],
    'scope-enum': [
      2,
      'always',
      [
        'cli',
        'common',
        'compression',
        'cookie',
        'core',
        'cors',
        'helmet',
        'http-adapter',
        'logger',
        'multipart',
        'query-parser',
        'rate-limiter',
        'result',
        'router',
        'shared',
        'tck',
        'examples',
        'benchmark',
        'example-stamp-middleware',
        'repo',
        'config',
        'ci',
        'deps',
        'release',
      ],
    ],
    'type-enum': [
      2,
      'always',
      ['build', 'chore', 'ci', 'docs', 'feat', 'fix', 'perf', 'refactor', 'revert', 'style', 'test'],
    ],
  },
};
